name: CI/CD
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        # Programmatic authentication to aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t react-docker:latest .
          docker tag react-docker:latest 318770414672.dkr.ecr.ap-southeast-1.amazonaws.com/react-docker:latest
          docker push 318770414672.dkr.ecr.ap-southeast-1.amazonaws.com/react-docker:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ec2-54-169-231-32.ap-southeast-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.AWS_SERVER_RSA }}
          script: |
            whoami
            aws ecr get-login-password --region ap-southeast-1 | sudo docker login --username AWS --password-stdin 318770414672.dkr.ecr.ap-southeast-1.amazonaws.com
            sudo docker pull 318770414672.dkr.ecr.ap-southeast-1.amazonaws.com/react-docker:latest
            sudo docker compose down
            sudo docker compose up
