name: CI/CD
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Connect To Server
        run: |
          echo "${{secrets.AWS_SERVER_RSA}}" > key.pem
          chmod 400 key.pem
          cat key.pem
