name: CI/CD
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Connect To Server
        run: |
          echo "${{secrets.AWS_SERVER_RSA}}" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${{secrets.AWS_EC2_SERVER}}
      - name: Login to AWS CLI
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{secrets.AWS_EC2_SERVER}} "aws ecr get-login-password --region ap-southeast-1 | sudo docker login --username AWS --password-stdin 318770414672.dkr.ecr.ap-southeast-1.amazonaws.com"
      - name: Pull Image
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{secrets.AWS_EC2_SERVER}} "sudo docker pull 318770414672.dkr.ecr.ap-southeast-1.amazonaws.com/react-docker:latest"
      - name: Stop docker compose
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{secrets.AWS_EC2_SERVER}} "sudo docker compose down"
      - name: Start docker compose
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{secrets.AWS_EC2_SERVER}} "sudo docker compose up -d"
