name: CI/CD
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        # Programmatic authentication to aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push image to Amazon ECR
        # copying the code from repo i.e. Dockerfile, versioning
        # the docker image, and pushing it to ECR.
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: bunserver
          IMAGE_TAG: latest
        run: |
          docker build -t react-docker .
