name: CI/CD
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        # Programmatic authentication to aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{secrets.ECR_REGISTRY}}
          ECR_REPOSITORY: react-docker
          IMAGE_TAG: latest
        run: |
          docker build -t react-docker:latest .
          docker tag react-docker:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker images
